# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 심심풀이땅콩의 개발 블로그
brief-intro: Sangdeok's Dev Note
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://deokudev.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: 
facebook_username: jsd2174@nate.com
github_username:  deokudev
email: sangdeok2174@naver.com
weibo_username: 
zhihu_username: 
linkedIn_username: 
dribbble_username:

description_footer: Dev_Blog

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
disqus_shortname: deokudev

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 
google_analytics_id: UA-111925711-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6

# prose setting
prose:
  rooturl: '_posts'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "date"
        field:
          element: "text"
          label: "date"
          value: CURRENT_DATETIME
      - name: "published"
        field:
          element: "hidden"
          value: true
      - name: "title"
        field:
          element: "text"
          placeholder: "2018-00-00-name.md"
          label: "title"  
      - name: "categories"
        field:
          element: "text"
          label: "categories"
          value: "etc"
      - name: "tags"
        field:
          element: "text"
          label: "tags"       
